name: STT Plugin PKGUILDS
on:
  workflow_dispatch:

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    container:
      image: manjarolinux/base:latest
    steps:
      - name: Install build Dependencies
        run: |
          useradd -m -g root build
          sudo pacman --noconfirm --needed -Sy pkgfile namcap python-pip python-setuptools git swig cython gcc-fortran base-devel fann cargo ninja python-google-api-core python-setuptools python-wheel python-pillow pkgconf llvm alsa-lib
          yes | LC_ALL=en_US.UTF-8 sudo pacman -S openblas
          pip install git+https://github.com/anntzer/pypi2pkgbuild
          pkgfile --update
      - name: gen PKGBUILDS
        run: |
          sudo -u build pypi2pkgbuild.py --base-path /tmp/build --force --no-install --pre ovos-stt-plugin-vosk
          sudo -u build pypi2pkgbuild.py --base-path /tmp/build --force --no-install --pre ovos-stt-plugin-server
          sudo -u build pypi2pkgbuild.py --base-path /tmp/build --force --no-install git+https://github.com/OpenVoiceOS/ovos-stt-http-server
          sudo -u build pypi2pkgbuild.py --base-path /tmp/build --force --no-install --no-deps --pre ovos-stt-plugin-whispercpp
          sudo -u build pypi2pkgbuild.py --base-path /tmp/build --force --no-install --no-deps --pre ovos-stt-plugin-fasterwhisper
          sudo -u build pypi2pkgbuild.py --base-path /tmp/build --force --no-install --pre ovos-stt-plugin-pocketsphinx
          sudo -u build pypi2pkgbuild.py --base-path /tmp/build --force --no-install --pre ovos-stt-plugin-selene
          sudo -u build pypi2pkgbuild.py --base-path /tmp/build --force --no-install --no-deps --pre git+https://github.com/OpenVoiceOS/ovos-stt-plugin-privox
          sudo -u build pypi2pkgbuild.py --base-path /tmp/build --force --no-install --no-deps --pre git+https://github.com/OpenVoiceOS/ovos-stt-plugin-whisper-tflite
          sudo -u build pypi2pkgbuild.py --base-path /tmp/build --force --no-install --no-deps --pre git+https://github.com/OpenVoiceOS/ovos-stt-plugin-whisper
          sudo -u build pypi2pkgbuild.py --base-path /tmp/build --force --no-install --no-deps --pre git+https://github.com/OpenVoiceOS/ovos-stt-plugin-deepgram
          sudo -u build pypi2pkgbuild.py --base-path /tmp/build --force --no-install --pre ovos-stt-plugin-chromium
      - uses: actions/checkout@v3
        with:
          ref: dev
      - name: Cleanup
        run: |
          (cd /tmp/build && tar c .) | (cd . && tar xf -)
          sudo rm -rf python-*/pkg
          sudo rm -rf python-*/src
          sudo rm -rf python-*/*.whl
          sudo rm -rf python-*/*.pkg.tar.zst
          ls
          git config --global --add safe.directory /__w/ovos-binary-shop/ovos-binary-shop
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: pkgbuild stt plugins
          add: 'python-* --force'
