name: OVOS core PKGUILDS
on:
  workflow_dispatch:

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    container:
      image: manjarolinux/base:latest
    steps:
      - name: Install build Dependencies
        run: |
          sudo pacman --noconfirm --needed -Sy pkgfile namcap python-pip git swig cython base-devel fann cargo ninja python-google-api-core python-setuptools python-wheel pkgconf
          pip install git+https://github.com/anntzer/pypi2pkgbuild
          pkgfile --update
      - name: gen PKGBUILDS
        #sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install --no-deps --pre ovos-bus
        run: |
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install --pre ovos-core
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install --pre ovos-messagebus
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install --pre ovos-gui
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install --pre ovos-skills-manager
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install --pre ovos_bus_client
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install --pre ovos-lingua-franca
      - uses: actions/checkout@v3
        with:
          ref: dev
      - name: Cleanup
        run: |
          (cd /tmp/build && tar c .) | (cd . && tar xf -)
          sudo rm -rf python-*/pkg
          sudo rm -rf python-*/src
          sudo rm -rf python-*/*.whl
          sudo rm -rf python-*/*.pkg.tar.zst
          ls
          git config --global --add safe.directory /__w/ovos-binary-shop/ovos-binary-shop
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: pkgbuild
          add: 'python-* --force'
