name: PHAL PKGUILDS
on:
  workflow_dispatch:

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    container:
      image: manjarolinux/base:latest
    steps:
      - name: Install build Dependencies
        run: |
          sudo pacman --noconfirm --needed -Sy pkgfile namcap python-pip git swig cython base-devel cargo gcc-fortran fann ninja python-google-api-core python-setuptools python-wheel python-pillow pkgconf alsa-lib
          yes | LC_ALL=en_US.UTF-8 sudo pacman -S openblas
          pip install git+https://github.com/anntzer/pypi2pkgbuild
          pkgfile --update
      - name: gen PKGBUILDS
          # already built with ovos-phal
          # sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install --pre ovos-PHAL-plugin-system
          # sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install --pre ovos-PHAL-plugin-color-scheme-manager
          # sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install --pre ovos-PHAL-plugin-network-manager
          # sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install --pre ovos-phal-plugin-ipgeo
          # sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install --pre ovos-PHAL-plugin-oauth
        run: |
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install --pre ovos-phal
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install --pre ovos-phal-plugin-connectivity-events
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install --pre ovos-PHAL-plugin-wallpaper-manager
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install --pre ovos-PHAL-plugin-brightness-control-rpi
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install --pre ovos-PHAL-plugin-alsa
      - uses: actions/checkout@v3
        with:
          ref: dev
      - name: Cleanup
        run: |
          (cd /tmp/build && tar c .) | (cd . && tar xf -)
          sudo rm -rf python-*/pkg
          sudo rm -rf python-*/src
          sudo rm -rf python-*/*.whl
          sudo rm -rf python-*/*.pkg.tar.zst
          ls
          git config --global --add safe.directory /__w/ovos-binary-shop/ovos-binary-shop
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: pkgbuild phal
          add: 'python-* --force'
