name: Skill PKGUILDS
on:
  push:
  workflow_dispatch:

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    container:
      image: manjarolinux/base:latest
    steps:
      - name: Install build Dependencies
        run: |
          echo "Y" | sudo pacman -Sy pkgfile namcap python-pip git
          pip install pypi2pkgbuild
          pkgfile --update
      - name: gen PKGBUILDS
        run: |
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install --no-deps --pre ovos-skill-volume~=0.0.1
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install --no-deps --pre ovos-skill-fallback-unknown~=0.0.2
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install --no-deps --pre ovos-skill-stop~=0.2
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install --no-deps --pre neon-skill-alerts~=1.2
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install --no-deps --pre ovos-skill-personal~=0.0, >=0.0.3
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install --no-deps --pre ovos-skill-naptime~=0.2, >=0.2.2
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install --no-deps --pre ovos-skill-date-time~=0.2, >=0.2.2
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install --no-deps --pre ovos-skill-hello-world~=0.0, >=0.0.3
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install --no-deps --pre ovos-skill-filebrowser~=0.0, >=0.0.2
      - uses: actions/checkout@v3
        with:
          ref: dev
      - name: Cleanup
        run: |
          (cd /tmp/build && tar c .) | (cd . && tar xf -)
          sudo rm -rf python-*/src
          sudo rm -rf python-*/*.whl
          sudo rm -rf python-*/*.pkg.tar.zst
          ls
          git config --global --add safe.directory /__w/ovos-binary-shop/ovos-binary-shop
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: pkgbuild skills
          add: 'python-* --force'