name: OVOS additional PKGUILDS
on:
  workflow_dispatch:

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    container:
      image: manjarolinux/base:latest
    steps:
      - name: Install build Dependencies
        run: |
          sudo pacman --noconfirm --needed -Sy pkgfile namcap python-pip git swig cython base-devel fann gcc-fortran cargo portaudio ninja python-google-api-core python-setuptools python-wheel python-pillow pkgconf llvm alsa-lib libjpeg-turbo openjpeg2 libtiff 
          yes | LC_ALL=en_US.UTF-8 sudo pacman -S openblas
          pip install git+https://github.com/anntzer/pypi2pkgbuild
          pkgfile --update
      - name: gen PKGBUILDS
        run: |
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install speechrecognition
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install bitstruct
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install pprintpp
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install beautifulsoup4
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install pako
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install pyaudio
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install pyalsaaudio
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install webrtcvad
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install pocketsphinx
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install petact
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install precise-runner
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install onnxruntime
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install --pre tutubo
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install yt-dlp
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install py-mplayer
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install py_bandcamp
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install deezeridu
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install requests-cache
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install wallpaper-finder
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install --pre ovos-skill-installer
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install precise-lite-runner
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install neon-mana-utils
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install sdnotify
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install timezonefinder
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install huggingface_hub
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install tokenizers
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install ctranslate2
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install tiktoken
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install ffmpeg-python
          sudo -u nobody pypi2pkgbuild.py --base-path /tmp/build --force --no-install feedparser


      - uses: actions/checkout@v3
        with:
          ref: dev
      - name: Cleanup
        run: |
          (cd /tmp/build && tar c .) | (cd . && tar xf -)
          sudo rm -rf python-*/pkg
          sudo rm -rf python-*/src
          sudo rm -rf python-*/*.whl
          sudo rm -rf python-*/*.pkg.tar.zst
          ls
          git config --global --add safe.directory /__w/ovos-binary-shop/ovos-binary-shop
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: pkgbuild additional
          add: 'python-* --force'
